#font_size 19

cursor_blink_interval 0

scrollback_lines 50000

show_hyperlink_targets yes
underline_hyperlinks always

tab_bar_edge top

#background_opacity 0.85

shell_integration no-cursor

#map ctrl+c copy_or_interrupt
map page_up scroll_page_up
map page_down scroll_page_down

map alt+shift+] next_tab
map alt+shift+[ previous_tab

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map ctrl+[ send_text all \x1b

